### ISSUE TITLE
The Kotlin Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by wk-j** [mathiasfrohlich/vscode-kotlin#24]
I got this notification in VS code.

```
The Kotlin Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

And try to follow the instruction in Developer Tools I got another message.

```
❯ /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home/bin/java -Xverify:none -jar /Users/wk/.vscode/extensions/georgewfraser.kotlin-0.1.0/target/KotlinLanguageServer.jar
Exception in thread "main" java.lang.IllegalStateException: LOGGING: Loading modules: [java.se, javafx.base, javafx.controls, javafx.fxml, javafx.graphics, javafx.media, javafx.swing, javafx.web, jdk.accessibility, jdk.attach, jdk.compiler, jdk.dynalink, jdk.httpserver, jdk.incubator.httpclient, jdk.jartool, jdk.javadoc, jdk.jconsole, jdk.jdi, jdk.jfr, jdk.jshell, jdk.jsobject, jdk.management, jdk.management.cmm, jdk.management.jfr, jdk.management.resource, jdk.net, jdk.packager, jdk.packager.services, jdk.plugin.dom, jdk.scripting.nashorn, jdk.sctp, jdk.security.auth, jdk.security.jgss, jdk.unsupported, jdk.xml.dom, oracle.desktop, oracle.net, java.base, java.sql, java.logging, java.xml, java.rmi, java.scripting, java.security.sasl, java.management, java.datatransfer, java.desktop, java.xml.crypto, java.prefs, java.instrument, java.naming, java.compiler, java.sql.rowset, java.management.rmi, java.security.jgss, jdk.internal.jvmstat, jdk.management.agent, jdk.jdwp.agent, jdk.internal.ed, jdk.internal.opt, jdk.internal.le, jdk.jdeps, jdk.jlink] (no MessageCollector configured)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.report(ClasspathRootsResolver.kt:314)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.report$default(ClasspathRootsResolver.kt:312)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.addModularRoots(ClasspathRootsResolver.kt:254)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.computeRoots(ClasspathRootsResolver.kt:124)
	at org.jetbrains.kotlin.cli.jvm.compiler.ClasspathRootsResolver.convertClasspathRoots(ClasspathRootsResolver.kt:79)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:233)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.<init>(KotlinCoreEnvironment.kt:117)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment$Companion.createForProduction(KotlinCoreEnvironment.kt:413)
	at org.javacs.kt.Compiler.<init>(Compiler.kt:46)
	at org.javacs.kt.CompilerClassPath.<init>(CompilerClassPath.kt:9)
	at org.javacs.kt.KotlinLanguageServer.<init>(KotlinLanguageServer.kt:14)
	at org.javacs.kt.MainKt.main(Main.kt:8)
```

**Comment by nishtahir** [comment]
Looks like you are reporting a bug for the wrong project 😄. You probably want to report this to [georgewfraser/kotlin-language-server](https://github.com/georgewfraser/kotlin-language-server)
