### ISSUE TITLE
The Kotlin Language Client server crashing

### ISSUE THREAD

**Issue by bravo4one** [mathiasfrohlich/vscode-kotlin#52]
I get error "The Kotlin Language Client server crashed 5 times in the last 3 minutes. The server will not be restarted." after installing the extension from the Store.

From log:

[2021-08-14 10:33:07.589] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/user001/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode-remote.remote-wsl-recommender/dist/extension.js
[2021-08-14 10:33:08.026] [exthost] [error] Activating extension fwcd.kotlin failed due to an error:
[2021-08-14 10:33:08.026] [exthost] [error] Error: Connection to server got closed. Server will not be restarted.
	at x.handleConnectionClosed (c:\Users\user001\.vscode\extensions\fwcd.kotlin-0.2.23\dist\extension.js:2:901723)
	at x.handleConnectionClosed (c:\Users\user001\.vscode\extensions\fwcd.kotlin-0.2.23\dist\extension.js:2:961797)
	at t (c:\Users\user001\.vscode\extensions\fwcd.kotlin-0.2.23\dist\extension.js:2:899498)
	at a.invoke (c:\Users\user001\.vscode\extensions\fwcd.kotlin-0.2.23\dist\extension.js:2:822637)
	at o.fire (c:\Users\user001\.vscode\extensions\fwcd.kotlin-0.2.23\dist\extension.js:2:823398)
	at X (c:\Users\user001\.vscode\extensions\fwcd.kotlin-0.2.23\dist\extension.js:2:810282)
	at a.invoke (c:\Users\user001\.vscode\extensions\fwcd.kotlin-0.2.23\dist\extension.js:2:822637)
	at o.fire (c:\Users\user001\.vscode\extensions\fwcd.kotlin-0.2.23\dist\extension.js:2:823398)
	at fireClose (c:\Users\user001\.vscode\extensions\fwcd.kotlin-0.2.23\dist\extension.js:2:831279)
	at Socket.<anonymous> (c:\Users\user001\.vscode\extensions\fwcd.kotlin-0.2.23\dist\extension.js:2:832864)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)

Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19043 (Windows 10 Pro)

Processor	Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz   3.00 GHz
Installed RAM	32.0 GB

Windows Edition	Windows 10 Pro
Version	21H1
Installed on	‎2021-‎03-‎12
OS build	19043.1165
Experience	Windows Feature Experience Pack 120.2212.3740.0

**Comment by nishtahir** [comment]
This project is not responsible for the language server implementation. You'd want to report your issue [here](https://github.com/fwcd/kotlin-language-server)
